import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import HeroBanner from '@/components/heroBanner'
import BookingBanner from '@/components/bookingBanner'
import Services from '@/components/services'
import Testimonials from '@/components/testimonials'
import Separator from '@/components/separator'
import Parteners from '@/components/parteners'
import Footer from '@/components/footer'
import CarDetail from '@/components/carDetail'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Taxi-Lille</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroBanner />
      <BookingBanner />
      <Services />
      <CarDetail />
      <Separator />
      <Testimonials />
      <Parteners />
      <Footer />
    </>
  )
}
